Traceback (most recent call last):
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/raid/localscratch/qfebvre/miniconda/lib/python3.9/site-packages/nbclient/client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import xarray as xr
ds = xr.open_mfdataset('data/prepared/input/*.nc', combine='nested',concat_dim='time')
ds
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mxarray[39;00m [38;5;28;01mas[39;00m [38;5;21;01mxr[39;00m
[0;32m----> 2[0m ds [38;5;241m=[39m [43mxr[49m[38;5;241;43m.[39;49m[43mopen_mfdataset[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata/prepared/input/*.nc[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mcombine[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mnested[39;49m[38;5;124;43m'[39;49m[43m,[49m[43mconcat_dim[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mtime[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      3[0m ds

File [0;32m/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/xarray/backends/api.py:1021[0m, in [0;36mopen_mfdataset[0;34m(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)[0m
[1;32m   1018[0m paths [38;5;241m=[39m _find_absolute_paths(paths, engine[38;5;241m=[39mengine, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m   1020[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m paths:
[0;32m-> 1021[0m     [38;5;28;01mraise[39;00m [38;5;167;01mOSError[39;00m([38;5;124m"[39m[38;5;124mno files to open[39m[38;5;124m"[39m)
[1;32m   1023[0m [38;5;28;01mif[39;00m combine [38;5;241m==[39m [38;5;124m"[39m[38;5;124mnested[39m[38;5;124m"[39m:
[1;32m   1024[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(concat_dim, ([38;5;28mstr[39m, DataArray)) [38;5;129;01mor[39;00m concat_dim [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:

[0;31mOSError[0m: no files to open
OSError: no files to open

