Traceback (most recent call last):
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/nbclient/client.py", line 654, in async_setup_kernel
    yield
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dt, t = pd.to_timedelta("1D"), pd.to_datetime('2019-05-15')
out_grid = outgrid.pipe(val.validate_latlon).ssh.pad(time=1, mode='edge').assign_coords(
    time=pd.date_range(t-dt, t+dt, freq=dt)
).to_dataset(name='ssh')
out_grid.to_netcdf('output.nc')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[16], line 2[0m
[1;32m      1[0m dt, t [38;5;241m=[39m pd[38;5;241m.[39mto_timedelta([38;5;124m"[39m[38;5;124m1D[39m[38;5;124m"[39m), pd[38;5;241m.[39mto_datetime([38;5;124m'[39m[38;5;124m2019-05-15[39m[38;5;124m'[39m)
[0;32m----> 2[0m out_grid [38;5;241m=[39m [43moutgrid[49m[38;5;241;43m.[39;49m[43mpipe[49m[43m([49m[43mval[49m[38;5;241;43m.[39;49m[43mvalidate_latlon[49m[43m)[49m[38;5;241;43m.[39;49m[43mssh[49m[38;5;241m.[39mpad(time[38;5;241m=[39m[38;5;241m1[39m, mode[38;5;241m=[39m[38;5;124m'[39m[38;5;124medge[39m[38;5;124m'[39m)[38;5;241m.[39massign_coords(
[1;32m      3[0m     time[38;5;241m=[39mpd[38;5;241m.[39mdate_range(t[38;5;241m-[39mdt, t[38;5;241m+[39mdt, freq[38;5;241m=[39mdt)
[1;32m      4[0m )[38;5;241m.[39mto_dataset(name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mssh[39m[38;5;124m'[39m)
[1;32m      5[0m out_grid[38;5;241m.[39mto_netcdf([38;5;124m'[39m[38;5;124moutput.nc[39m[38;5;124m'[39m)

File [0;32m/raid/localscratch/qfebvre/ocb/ocb-docs/lib/python3.11/site-packages/xarray/core/common.py:285[0m, in [0;36mAttrAccessMixin.__getattr__[0;34m(self, name)[0m
[1;32m    283[0m         [38;5;28;01mwith[39;00m suppress([38;5;167;01mKeyError[39;00m):
[1;32m    284[0m             [38;5;28;01mreturn[39;00m source[name]
[0;32m--> 285[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m    286[0m     [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mtype[39m([38;5;28mself[39m)[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m!r}[39;00m[38;5;124m object has no attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m"[39m
[1;32m    287[0m )

[0;31mAttributeError[0m: 'DataArray' object has no attribute 'ssh'

